# -*- coding: utf-8 -*-
"""pertemuan_strukturdara5searching.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i4gXJfm61vfiYSRGqpOgcaXysS2V2R3-
"""

#linier search
def LinierSearch(arr, N, x):

  for i in range(0, N):
    if (arr[i] == x):
      return i
  return -1

#driver code
if __name__ == "__main__":
  arr = [20, 10, 30, 50, 40]
  x = 10
  N = len(arr)

  #function call
  result = LinierSearch(arr, N, x)
  if(result == -1):
    print("Element not found")
  else:
    print("Element found at index: ", result)

#binary search
def binarySearch(arr, l, r, x):
  while l <= r:
    mid = l + (r - l) // 2

    #check if x is present at mid
    if arr[mid] == x:
      return mid

    #if x is greater, ignore left half
    elif arr[mid] < x:
      l = mid + 1
    #if x is smaller, ignore right half
    else:
      r = mid - 1

  #if we reach here, then the element wasn't present
  return -l

#driver code
if __name__ == "__main__":
  arr = [2, 5, 8, 12, 16, 23, 38, 56, 72, 91]
  x = 72

  # function call
  result = binarySearch(arr, 0, len(arr)-1, x)
  if result != -1:
    print("Element is present at index", result)
  else:
    print("Element is not present in array")

#binary search dengan rekursif
def binarySearch(arr, l, r, x):

  #check base case
  if r >= l:
    mid = l + (r - l) // 2

    #if element is present in the middle
    if arr[mid] == x:
      return mid

    #if element is smaller than mid, it can only be present in left subarray
    elif arr[mid] > x:
      return binarySearch(arr, l, mid-1, x)

    #other than that, the element can only be present in right subarray
    else:
      return binarySearch(arr, mid+1, r, x)

  #element is not present in the array
  else:
    return -1

#driver code
if __name__ == "__main__":
  arr = [2, 5, 8, 12, 16, 23, 38, 56, 72, 91]
  x = 72

  #function call
  result = binarySearch(arr, 0, len(arr)-1, x)

  if result != -1:
    print("Element is present at index", result)
  else:
    print("Element is not present in array")

#jump search
import math

def jumpSearch(arr, x, n):
  #finding block size to be jumped
  step = math.sqrt(n)

  #finding thr block there the element is present
  prev = 0
  while arr[int(min(step, n)-1)] < x:
    prev = step
    step += math.sqrt(n)
    if prev >= n:
      return -1

  #doing a linear search for x in block beginning with prev.
  while arr[int(prev)] < x:
    prev += 1

    #if we reached next block or end of array, element is not present
    if prev == min(step, n):
      return -1

  #if element is found
  if arr[int(prev)] == x:
    return prev

  return -1

#driver code
arr = [0,1,1,2,3,5,8,13,21,34,55,89,144,233,377,610]
x = 55
n = len(arr)

#find the index of 'x' using jump search
index = jumpSearch(arr, x, n)

print("Number" , x, "is at index" , "%.0f"%index)

#studi kasus linier search

class pair:
  def __init__(self) -> None:
    self.min = 0
    self.max = 0

def getminmax(arr: list[int], n: int) -> pair:
  minmax = pair()

  if n == 1:
    minmax.max = arr[0]
    minmax.min = arr[0]
    return minmax

  if arr[0] > arr[1]:
    minmax.max = arr[0]
    minmax.min = arr[1]
  else:
    minmax.max = arr[1]
    minmax.min = arr[0]

  for i in range(2, n):
    if arr[i] > minmax.max:
      minmax.max = arr[i]
    elif arr[i] < minmax.min:
      minmax.min = arr[i]

  return minmax
# driver code
if __name__ == "__main__":
  arr = [1000,11,445,1,330,3000]
  arr_size = 6
  minmax = getminmax(arr, arr_size)
  print("Minimum element is", minmax.min)
  print("Maximum element is", minmax.max)