# -*- coding: utf-8 -*-
"""pertemuan_strukturdata4Queue.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EVnEIMNPEItFwZF9_T6s9X_h_jvbB1-p
"""

#queue dengan list
queue = []

queue.append('a')
queue.append('b')
queue.append('c')
queue.append('d')
queue.append('e')

print("queue awal: ")
print(queue)

print("\nItem yang keluar: ")
print(queue.pop(0))
print(queue.pop(0))
print(queue.pop(0))

print("\nQueue akhir: ")
print(queue)

#queue dengan collections.deque
from collections import deque

queue = deque()

queue.append('a')
queue.append('b')
queue.append('c')
queue.append('d')
queue.append('e')

print("queue awal: ")
print(queue)

print("\nItem yang keluar: ")
print(queue.popleft())
print(queue.popleft())
print(queue.popleft())

print("\nQueue akhir: ")
print(queue)

#queue dengan queue.queue
from queue import Queue

qu = Queue(maxsize=5)

print(qu.qsize())

qu.put('a')
qu.put('b')
qu.put('c')
qu.put('d')
qu.put('e')

print("Full :", qu.full())
print("Ukuran :", qu.qsize())

print("\nItem yang keluar: ")
print(qu.get())
print(qu.get())
print(qu.get())

print("\nKosong?", qu.empty())
print("Full?", qu.full())

#queue dengan single linked list
class Queue:
  def __init__(self):
    self.queue = list()

  def addtoqu(self,dataval):
    if dataval not in self.queue:
      self.queue.insert(0,dataval)
      return True
    return False

  def removefromq(self):
    if len(self.queue)>0:
      return self.queue.pop()
    return ("No elements in Queue!")

  def size(self):
    return len(self.queue)

TheQueue = Queue()
print(TheQueue.addtoqu("Mon"))
print(TheQueue.addtoqu("Tue"))
print(TheQueue.addtoqu("Wed"))
print(TheQueue.addtoqu("Thu"))
print(TheQueue.size())
print(TheQueue.removefromq())
print(TheQueue.removefromq())
print(TheQueue.size())