# -*- coding: utf-8 -*-
"""praktikum_strukturdata8graph.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ukZ3dyOa3tt_93e8_360IMOISdXrXdgm
"""

graph = {
    'A':['B','C'],
    'B':['A','D','E'],
    'C':['A','F'],
    'D':['B'],
    'E':['B','F'],
    'F':['C','E']
}

def print_graph(graf):
    for node in graf:
        print(f"{node} -> {graf[node]}")

print_graph(graph)

from collections import deque

def bfs(graph, start):
    visited = set()
    queue = deque([start])

    while queue:
        vertex = queue.popleft()
        if vertex not in visited:
            print(vertex, end=" ")
            visited.add(vertex)
            queue.extend([neighbor for neighbor in graph[vertex] if neighbor not in visited])

bfs(graph, 'A')

def dfs(graph, start, visited=None):
    if visited is None:
        visited = set()

    if start not in visited:
        print(start, end=" ")
        visited.add(start)
        for neighbor in graph[start]:
            dfs(graph, neighbor, visited)

dfs(graph, 'A')

# Lengkapi fungsi untuk menghitung jumlah tetangga dari tiap simpul dalam graf
def count_neighbors(graph):
    result = {}
    for node in graph:
        # Menghitung jumlah elemen dalam daftar tetangga untuk simpul tersebut
        result[node] = len(graph[node])
    return result

#contoh graph
graf_contoh = {
    'A': ['B', 'C'],
    'B': ['A', 'D', 'E'],
    'C': ['A', 'F'],
    'D': ['B'],
    'E': ['B', 'F'],
    'F': ['C', 'E']
}
print(count_neighbors(graf_contoh))

#1 graph tak terarah
graf = {
    "A":["C","F"],
    "B":["A","C","D"],
    "C":["F"],
    "D":["B","D","E"],
    "E":["A","F","D"],
    "F":["C","A","B"],
}
# fungsi untuk menampilkan simpul dan edge
def printgraf(graf):
  for node in graf:
    print(f"{node} -> {graf[node]}")

#2 traversal bfs dan dfs
#bfs
from collections import deque
def bfs (graf,start):
  visited=set()
  queue=deque([start])

  while queue:
    vertex = queue.popleft()
    if vertex not in visited:
      print(vertex, end=' ')
      visited.add(vertex)
      queue.extend([neighbor for neighbor in graf[vertex] if neighbor
                   not in visited])


#dfs
def dfs (graf, start, visited=None):
  if visited==None:
    visited=set()

  if start not in visited:
    print(start, end=' ')
    visited.add(start)
    for neighbor in graf[start]:
      dfs(graf,neighbor, visited)
  return visited

#3 memodifikasi BFS agar mengembalikan list urutan kunjungannya
from collections import deque

def bfs_mod (graf,start):
  visited=set()
  queue=deque([start])

  while queue:
    vertex = queue.popleft()
    if vertex not in visited:
      print(vertex, end=' ')
      visited.add(vertex)
      queue.extend([neighbor for neighbor in graf[vertex] if neighbor
                   not in visited])
      print(visited) #ini modifikasinya

#4 membuat fungsi find_path
def find_path(graph, start, end, path=[]):
  path = path + [start]
  if start == end:
    return path
  if start not in graph:
      return None
  for neighbor in graph[start]:
      if neighbor not in path:
          new_path = find_path(graph, neighbor, end, path)
          if new_path:
            return new_path
  return None


print('\n=========== FIND PATH =============')
jalur_start_ke_end = find_path(graf, 'V', 'Y')
print(f"Satu jalur dari V ke Y: {jalur_start_ke_end}")

#5 membuat fungsi is_connected
def is_connected(graph):
    if not graph:
        return True
    visited = set()

    def dfs(node):
        visited.add(node)
        for neighbor in graph.get(node, []):
            if neighbor not in visited:
                dfs(neighbor)
    start_node = next(iter(graph))
    dfs(start_node)

    return len(visited) == len(graph)

#contoh graph
graph_connected = {
    'A': ['B'],
    'B': ['A', 'C'],
    'C': ['B']
}

print("Apakah graph_connected terhubung?", is_connected(graph_connected))